// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3PcaslkdIIERCkasBz9Ky00s09-K-qM',
    appId: '1:71697718932:web:d5b2df59d23839a7fbde81',
    messagingSenderId: '71697718932',
    projectId: 'crud-notes-84320',
    authDomain: 'crud-notes-84320.firebaseapp.com',
    storageBucket: 'crud-notes-84320.firebasestorage.app',
    measurementId: 'G-YL4NLP4D67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXFKFR0LxNuPbXHUhyd0iYkvACQBRsV4',
    appId: '1:71697718932:android:9072225dfaf6ce3bfbde81',
    messagingSenderId: '71697718932',
    projectId: 'crud-notes-84320',
    storageBucket: 'crud-notes-84320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwq192_fGSapEEwPq5Hx7ax3fj5yuzCGA',
    appId: '1:71697718932:ios:1de9ba39ce01815cfbde81',
    messagingSenderId: '71697718932',
    projectId: 'crud-notes-84320',
    storageBucket: 'crud-notes-84320.firebasestorage.app',
    iosBundleId: 'com.example.aliHassan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwq192_fGSapEEwPq5Hx7ax3fj5yuzCGA',
    appId: '1:71697718932:ios:1de9ba39ce01815cfbde81',
    messagingSenderId: '71697718932',
    projectId: 'crud-notes-84320',
    storageBucket: 'crud-notes-84320.firebasestorage.app',
    iosBundleId: 'com.example.aliHassan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3PcaslkdIIERCkasBz9Ky00s09-K-qM',
    appId: '1:71697718932:web:8efd9657d5f3fee5fbde81',
    messagingSenderId: '71697718932',
    projectId: 'crud-notes-84320',
    authDomain: 'crud-notes-84320.firebaseapp.com',
    storageBucket: 'crud-notes-84320.firebasestorage.app',
    measurementId: 'G-KVT2Y640FZ',
  );
}
